apiVersion: v1
kind: Service
metadata:
  name: wil42-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: wil42
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
  type: NodePort
